### PR TITLE
Move memory event source to specs

### PR DESCRIPTION
**Pull request by corvansteijn**
The MemoryEventSource is not meant to be used in production code

### CODE REVIEW

**Comment by IharBury** [comment]
@corvansteijn, @dennisdoomen, how should we write tests in projects that use LiquidProjections? Should we create our own MemoryEventSources?

**Comment by dennisdoomen** [comment]
That's why I kept that thing in the project, but it was never meant to be used in production environments. Maybe it should become a separate package?

**Comment by corvansteijn** [comment]
Or we could make it ready for production use. Although I cannot think of a real scenario outside testing. 

For now, I have created an implementation in vision suite (needed a fix and did not want to wait for the merge anyway)

**Comment by dennisdoomen** [comment]
Replaced by #67

**Pull request closed without merging**
